package com.example.mediqueue.controller;
import com.example.mediqueue.model.*;import com.example.mediqueue.repository.*;import com.example.mediqueue.service.NotificationService;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;
@Controller @RequestMapping("/doctor/clinical") public class ClinicalController{
 private final AppointmentRepository ar;private final UserRepository ur;private final ConsultationRepository cr;private final MedicalRecordRepository mr;private final PrescriptionRepository pr;private final NotificationService ns;private final PatientRepository patientRepository;
 public ClinicalController(AppointmentRepository a,UserRepository u,ConsultationRepository c,MedicalRecordRepository m,PrescriptionRepository p,NotificationService n,PatientRepository patientRepository){ar=a;ur=u;cr=c;mr=m;pr=p;ns=n;this.patientRepository=patientRepository;}
 private Doctor me(Authentication a){return ur.findByUserId(a.getName()).map(User::getDoctor).orElse(null);}
 @GetMapping("/consultation/{id}") public String form(@PathVariable Long id,Authentication a,Model m){Doctor d=me(a);Appointment ap=ar.findById(id).orElseThrow();if(d==null||ap.getDoctor()==null||!ap.getDoctor().getId().equals(d.getId()))return "redirect:/doctor/appointments";m.addAttribute("appointment",ap);m.addAttribute("consultation",cr.findByAppointment_Id(id).orElse(new Consultation()));return "clinical/consultation";}
 @PostMapping("/consultation/{id}") public String save(@PathVariable Long id,@RequestParam String diagnosis,@RequestParam String notes,Authentication a){Doctor d=me(a);Appointment ap=ar.findById(id).orElseThrow();if(d==null||ap.getDoctor()==null||!ap.getDoctor().getId().equals(d.getId()))return "redirect:/doctor/appointments";Consultation c=cr.findByAppointment_Id(id).orElse(new Consultation());c.setAppointment(ap);c.setDiagnosis(diagnosis);c.setNotes(notes);cr.save(c);ns.notifyStaffAndAdmin("CLINICAL", "Clinical notes updated for "+ap.getPatient().getFullName()+" by Dr. "+d.getFullName()+".");return "redirect:/doctor/clinical/consultation/"+id;}
 @GetMapping("/records/{patientId}") public String records(@PathVariable Long patientId,Authentication a,Model m){Doctor d=me(a);if(d==null||!hasPatient(d,patientId))return "redirect:/doctor/appointments";m.addAttribute("patient",patientRepository.findById(patientId).orElse(null));m.addAttribute("records",mr.findByPatient_IdOrderByCreatedAtDesc(patientId));m.addAttribute("prescriptions",pr.findByPatient_IdOrderByCreatedAtDesc(patientId));return "clinical/records";}
 @PostMapping("/records/{patientId}") public String addRecord(@PathVariable Long patientId,@RequestParam String diagnosis,@RequestParam String notes,Authentication a){Doctor d=me(a);if(d==null||!hasPatient(d,patientId))return "redirect:/doctor/appointments";Patient p=patientRepository.findById(patientId).orElseThrow();MedicalRecord r=new MedicalRecord();r.setPatient(p);r.setDoctor(d);r.setDiagnosis(diagnosis);r.setNotes(notes);mr.save(r);return "redirect:/doctor/clinical/records/"+patientId;}
 @PostMapping("/prescriptions/{patientId}") public String prescription(@PathVariable Long patientId,@RequestParam String medicines,@RequestParam String instructions,Authentication a){Doctor d=me(a);if(d==null||!hasPatient(d,patientId))return "redirect:/doctor/appointments";Patient p=patientRepository.findById(patientId).orElseThrow();Prescription r=new Prescription();r.setPatient(p);r.setDoctor(d);r.setMedicines(medicines);r.setInstructions(instructions);pr.save(r);return "redirect:/doctor/clinical/records/"+patientId;}
 private boolean hasPatient(Doctor d,Long patientId){return ar.findAll().stream().anyMatch(x->x.getDoctor()!=null&&x.getDoctor().getId().equals(d.getId())&&x.getPatient()!=null&&x.getPatient().getId().equals(patientId));}
}
