package com.example.mediqueue.controller;
import com.example.mediqueue.model.*;import com.example.mediqueue.repository.*;import com.example.mediqueue.service.NotificationService;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;
@Controller @RequestMapping("/facilities") public class FacilityController{
 private final OpdRepository or;private final RoomBedRepository rr;private final DepartmentRepository dr;private final DoctorRepository doctors;private final PatientRepository pr;private final NotificationService ns;
 public FacilityController(OpdRepository o,RoomBedRepository r,DepartmentRepository d,DoctorRepository ds,PatientRepository p,NotificationService n){or=o;rr=r;dr=d;doctors=ds;pr=p;ns=n;}
 @GetMapping public String page(Model m){m.addAttribute("opds",or.findAll());m.addAttribute("beds",rr.findAll());m.addAttribute("departments",dr.findAll());m.addAttribute("doctors",doctors.findAll());m.addAttribute("patients",pr.findAll().stream().filter(Patient::isActive).toList());return "facilities";}
 @PostMapping("/opd") public String addOpd(@RequestParam String name,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long doctorId,@RequestParam(required=false)String roomNumber){Opd o=new Opd();o.setName(name);if(departmentId!=null)o.setDepartment(dr.findById(departmentId).orElse(null));if(doctorId!=null)o.setDoctor(doctors.findById(doctorId).orElse(null));o.setRoomNumber(roomNumber);or.save(o);ns.notifyStaffAndAdmin("OPD","OPD "+name+" was created.");return "redirect:/facilities";}
 @PostMapping("/opd/{id}/toggle") public String toggleOpd(@PathVariable Long id){or.findById(id).ifPresent(o->{o.setOpen(!o.isOpen());or.save(o);ns.notifyStaffAndAdmin("OPD","OPD "+o.getName()+" is now "+(o.isOpen()?"OPEN":"CLOSED")+".");});return "redirect:/facilities";}
 @PostMapping("/bed") public String addBed(@RequestParam String roomNumber,@RequestParam String bedNumber,@RequestParam(required=false)String ward){RoomBed b=new RoomBed();b.setRoomNumber(roomNumber);b.setBedNumber(bedNumber);b.setWard(ward);rr.save(b);ns.notifyStaffAndAdmin("BED","Bed "+roomNumber+"/"+bedNumber+" added.");return "redirect:/facilities";}
 @PostMapping("/bed/{id}/assign") public String assign(@PathVariable Long id,@RequestParam Long patientId){rr.findById(id).ifPresent(b->{Patient p=pr.findById(patientId).orElse(null);b.setPatient(p);b.setOccupied(p!=null);rr.save(b);ns.notifyStaffAndAdmin("BED","Bed "+b.getRoomNumber()+"/"+b.getBedNumber()+" is now "+(b.isOccupied()?"occupied by "+p.getFullName():"available")+".");});return "redirect:/facilities";}
 @PostMapping("/bed/{id}/release") public String release(@PathVariable Long id){rr.findById(id).ifPresent(b->{b.setPatient(null);b.setOccupied(false);rr.save(b);ns.notifyStaffAndAdmin("BED","Bed "+b.getRoomNumber()+"/"+b.getBedNumber()+" is now available.");});return "redirect:/facilities";}
}
